name: Regenerate PluginMaster
on: 
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  generate:
    name: Regenerate PluginMaster
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - uses: actions/checkout@v2
      - name: Generate PluginMaster
        run: python generate_pluginmaster.py
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate PluginMaster
      - uses: Ilshidur/action-discord@master